---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS Network Firewall controller is a service controller for managing Network Firewall resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Network Firewall
description: |-
  Manage Amazon Network Firewall resources in AWS from within your Kubernetes cluster.


  **About Amazon Network Firewall**


  AWS Network Firewall is a stateful, managed, network firewall and intrusion detection and prevention service for your virtual private cloud (VPC) that you create in Amazon Virtual Private Cloud (Amazon VPC).
  
  With Network Firewall, you can filter traffic at the perimeter of your VPC. This includes filtering traffic going to and coming from an internet gateway, NAT gateway, or over VPN or AWS Direct Connect. 
  Network Firewall uses the open source intrusion prevention system (IPS), Suricata, for stateful inspection. Network Firewall supports Suricata compatible rules. For more information, 
  see [Working with stateful rule groups in AWS Network Firewall](https://docs.aws.amazon.com/network-firewall/latest/developerguide/stateful-rule-groups-ips.html).


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: RuleGroup
  spec: '{}'
- kind: FirewallPolicy
  spec: '{}'
- kind: Firewall
  spec: '{}'
maintainers:
- name: "network firewall maintainer team"
  email: "ack-maintainers@amazon.com"
links: 
- name: Amazon Network Firewall Developer Resources
  url: https://aws.amazon.com/network-firewall/resources/
